# Generated by Django 5.1.4 on 2025-02-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentmethod_subscriptionduration_subscriptiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Periyot Başlangıcı')),
                ('period_end', models.DateField(verbose_name='Periyot Bitişi')),
                ('status', models.CharField(choices=[('pending', 'Ödeme Bekleniyor'), ('paid', 'Ödeme Yapıldı')], default='pending', max_length=10, verbose_name='Ödeme Durumu')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='core.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Ödeme Kaydı',
                'verbose_name_plural': 'Ödeme Kayıtları',
                'ordering': ['period_start'],
            },
        ),
    ]
