# Generated by Django 5.1.4 on 2025-02-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customer_tax_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi Adresi'),
        ),
    ]
