# Generated by Django 5.1.4 on 2025-02-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_tax_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('talep', 'Talep'), ('istek', 'İstek'), ('sikayet', 'Şikayet')], max_length=20, verbose_name='Kayıt Türü')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('pending', 'Çözülmedi / Beklemede'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü / Tamamlandı')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.customer', verbose_name='Müşteri')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen Temsilci')),
            ],
            options={
                'verbose_name': 'Talep / İstek / Şikayet',
                'verbose_name_plural': 'Talepler / İstekler / Şikayetler',
                'ordering': ['-created_at'],
            },
        ),
    ]
