# Generated by Django 5.1.4 on 2025-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_address',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Vergi Adresi'),
        ),
    ]
