# Generated by Django 5.1.4 on 2025-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customerrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çözülme Tarihi'),
        ),
    ]
